name: Deploy frontend on Vercel

on:
  release:
    types: [prereleased]
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-event

env:
  CARGO_TERM_COLOR: always
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [fmt, clippy]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  build-and-preview-deploy:
    runs-on: ubuntu-latest
    name: Build and Preview

    needs: [test, clippy, fmt]

    permissions:
      pull-requests: write

    environment:
      name: pre_production
      url: ${{ steps.pre_production.outputs.preview-url }}

    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: rustup target add wasm32-unknown-unknown

      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.2/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-


      - name: Get Last Successful Run ID
        id: get_run_id
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_GH_TOKEN }}
          script: |
            const owner = '${{ vars.BEVY_OWNER }}';
            const repo = '${{ vars.BEVY_REPO }}';
            const workflow_id = '${{ vars.BEVY_PRERELEASE_WORKFLOW }}';

            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id,
              status: 'success',
              per_page: 1,
              page: 1
            });

            console.log('Workflow runs response:', runs);

            if (runs.data.workflow_runs.length > 0) {
              core.setOutput('run_id', runs.data.workflow_runs[0].id);
            } else {
              core.setFailed('No successful runs found.');
            }

      - uses: actions/download-artifact@v4
        with:
          name: preview-artifact
          github-token: ${{ secrets.ORG_GH_TOKEN }}
          repository: ${{ vars.BEVY_OWNER }}/${{ vars.BEVY_REPO }}
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          path: preview-artifact

      - name: Move artifact to public
        run: |
          mkdir -p public
          mv preview-artifact/* public/

      - name: Build with Trunk
        run: ./trunk build --release

      - name: Preview Deploy
        id: pre_production
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: false
          working-directory: ./dist

      - name: Display Deployed URL
        run: |
          echo "Deployed app URL: ${{ steps.pre_production.outputs.preview-url }}" >> $GITHUB_STEP_SUMMARY
